### PR TITLE
Add another alternative

### PR DESCRIPTION
**Pull request by praisedpk**
Add PageCDN as alternative. PageCDN is secure and has the following features:

- hsts preloaded
- manual review process for libraries and other opensource stuff
- full control over edge servers and cache
- strict eye over malware with formal [malware reporting ](https://pagecdn.com/about/malware)and review mechanism
- better compression ratio with **brotli-11 compression**. This reduces file size by upto 29% for compressible resources. A good example is font-awesome's `all.min.js` file.

````
 331.12 KB    https://pagecdn.io/lib/font-awesome/5.10.0-11/js/all.min.js
 385.72 KB    https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0-11/js/all.min.js
 459.39 KB    https://use.fontawesome.com/releases/v5.10.0-11/js/all.js (named all.js on this CDN)
1105.92 KB    Raw all.js file
````

Site: https://pagecdn.com/

### CODE REVIEW

**Comment by jimaek** [comment]
This CDN seems to have a very limited list of libraries and is in no way an alternative to rawgit that supports every single github file. Also I would give it a few years to see the stability.

**Comment by praisedpk** [comment]
Yes @jimaek that's intentional, to make sure the platform remains clean. But the library list is still not that limited. We cover almost all popular libraries and frameworks, and around 1900 WordPress themes. We are also open to users suggestions and actively do surveys to know which libraries users want on the platform.

About the stability: We have been testing it since October 2018, and opened it for everyone on 2nd of May 2019. Still we waited for more and more feedback and the formal launch was announced on 8th of July after dealing with all known bugs. Yes, its still not as proven as your [jsDelivr](https://github.com/jimaek) is, but it is stable, production ready and we are satisfied with the quality of our platform. We have transitioned almost all of our clients' and personal websites to PageCDN in the last 2 months.

PageCDN has some features that no other CDN currently offers. This has attracted very positive feedback in our surveys and we are committed to maintain and improve that feedback and stability level.

Hopefully this clears any doubts.

**Comment by praisedpk** [comment]
We initially wanted to link to github as rawgit and jsDelivr do. However, we changed our decision at the point when we saw many github repos containing malware or content for adult ad campaigns toping the [jsDelivr stats API](https://github.com/jsdelivr/data.jsdelivr.com#get-the-most-popular-packages) a few years back.

Another reason why we dropped the idea is because quality level 11 of brotli pre-compression is really really expensive. We can afford to provide it if a library is used by many websites, but its not feasible to support it for every possible commit of every possible github repo.

Still, it doesn't mean we are limited to a fixed set of libraries. We are adding more libraries daily and maybe by the end of this year our library list will match that of CDNJS in size.

**Comment by neoascetic** [comment]
If that's a real CDN why isn't it accessible from Russia?

**Comment by rgrove** [comment]
@praisedpk Thanks, but I'm only comfortable recommending services I know well and can personally vouch for. Best of luck with PageCDN.

**Pull request closed without merging**
