### PR TITLE
Added most used RDF formats

### PR DESCRIPTION
**Pull request by l00mi**
Pretty please?

Reference: http://en.wikipedia.org/wiki/Semantic_Web

### CODE REVIEW

**Comment by ktk** [comment]
n3 should be `text/n3;charset=utf-8`, beside this big +1 for merge :-)

**Comment by rgrove** [comment]
@l00mi Thanks for the PR! I plan to merge this, but first I think I'd like to switch to using [`mime-types`](https://github.com/jshttp/mime-types) instead of [`mime`](https://github.com/broofa/node-mime). Give me a day or two to make that happen.

**Comment by l00mi** [comment]
Great! no hurry (-,

ml

**Comment by rgrove** [comment]
Done! Ended up being easier than expected. :)

**Comment by l00mi** [comment]
Fantastic! Thanks a lot.

**Pull request closed without merging**
