### PR TITLE
Add raw.githack.com to the list of alternatives

### PR DESCRIPTION
**Pull request by neoascetic**
raw.githack.com was initially inspired by and for a long period of time tried to mimic RawGit. 
Could it try to be one of the official alternatives as the last tribute to RawGit?

### CODE REVIEW

**Comment by rgrove** [comment]
Hey Pavel! I'm aware of raw.githack.com and several other RawGit workalikes, but the reason I didn't list them as alternatives is that they all have the same problem RawGit has: serving HTML as `text/html` makes them easy distribution channels for malware, phishing attempts, and other forms of abuse.

The primary reason I'm shutting RawGit down is that I think it's fundamentally irresponsible to run a service like this without taking proactive and comprehensive steps to prevent abuse, so I'm not comfortable recommending alternatives that have the same problem.

Are you able to commit to taking proactive and comprehensive measures to prevent abuse? If so, could you describe them?

**Comment by neoascetic** [comment]
But Github Pages has the same issue as well, doesn’t it? Is the only problem with `text/html`? Couldn’t you just disable it then instead of shutting the service down?

**Comment by rgrove** [comment]
There are a few factors that make this less of a problem for GitHub Pages:

-   GitHub has good abuse reporting mechanisms and dedicated staff who handle abuse reports and work to proactively prevent abuse.

-   GitHub Pages doesn't serve content with immutable or far-future cache expiration headers, so when malware is removed from GitHub, it quickly stops being a problem. A big problem for RawGit was that malware could stick around in CDN and browser caches for up to a year even after being removed from GitHub.

-   GitHub Pages requires some actual effort to use. I think the primary factor in why RawGit was so attractive as a malware distribution channel is that it was dead simple.

I did consider simply disabling `text/html` support, but that was the primary differentiator between RawGit and free CDNs like jsDelivr. Without `text/html` support, there's really not much reason for RawGit to exist, because there are much better free CDNs for serving other static files. And `application/javascript` is still a big avenue for abuse (cryptocurrency miners are a big problem), so would still require frequent manual intervention.

At small scale, a one-person hobby project can probably handle abuse just fine, but at the scale RawGit reached, it really needed multiple people with the time and expertise to proactively identify and prevent abuse.

Seeing RawGit used to spread malware that crashed iOS devices a few weeks ago was a real wake-up call for me. RawGit made it way too easy for someone to rapidly cause a lot of harm before I was even aware of the problem, and once I became aware, I had to drop everything to fix it. That just doesn't scale, for me or for any other hobbyist.

**Comment by neoascetic** [comment]
Pretty fair. Thank you!

**Pull request closed without merging**
